name: Build and Test

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - uses: Vipul-Cariappa/lua-setup-action@main

    - name: Install Requirements
      run: |
        which python3
        which lua
    
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
          languages: cpp

    - name: Build
      run: bash .github/build.sh

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

    - name: Test
      run: bash .github/test.sh

    - name: Code Coverage
      run: |
        gcov -abcfu obj/Debug/c_string.c
        gcov -abcfu obj/Debug/lua_py.c
        gcov -abcfu obj/Debug/py_lua.c
        gcov -abcfu obj/Debug/convert.c

    - name: Upload Code Coverage
      uses: codecov/codecov-action@v1

