name: Build and Test

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - uses: leafo/gh-actions-lua@v8.0.0

    - name: Install Requirements
      run: sudo apt install -y gcc
      run: pkg-config python3-embed --cflags
      run: pkg-config lua --cflags
    - name: Build
      run: bash build.sh

    - name: Test
      run: bash test.sh
